### ISSUE TITLE
Option to include all existing databases

### ISSUE THREAD

**Issue by mvdriel** [Oefenweb/ansible-mydumper-backup#7]
What do you think of an option to include all existing databases (without specifying them all explicitly)?

**Comment by tersmitten** [comment]
I've thought of that, but I don't know if `mydumper` works well with non-InnoDB tables (like in the `mysql` table)

Maybe an `all` option with `ignore`?

Also, how would you like to get list of all tables?

**Comment by mvdriel** [comment]
The default behaviour of mydumper is to dump all databases; the database parameter is optional.

@tersmitten What do you think of implementing the same behaviour in this role?

**Comment by tersmitten** [comment]
I like this feature, but all the dump are in the same directory now. I remember that I had trouble with that.

**Comment by tersmitten** [comment]
I rather implement this as:

For backup:
- Getting a list of all database(s) (call `mysql` client)
- Use the regular loop

For restore:
- Getting a list of all backup(s) (use `ls` or `find`)
- Use the regular loop

**Comment by mvdriel** [comment]
@tersmitten How about dumping to a single directory and optionally moving to different directories per database afterwards?
This would preserve the parallel behaviour of mydumper for multiple databases.

**Comment by tersmitten** [comment]
We can use `mydumper --regex '^(?!(mysql|test))'` to exclude databases (in `ignore` list).

Dump in one directory create directories for the databases and move the file in there. Afterward copy the metadata file in all directories. This will make them all valid mydumper backups.

What would you do for restore? The reverse?

**Comment by tersmitten** [comment]
http://minimul.com/using-mydumpers-regex-switch-to-only-dump-certain-tables.html

**Comment by tersmitten** [comment]
Fixed in #15
